name: date
description: Hour, Date, Month implementations for Dart and other time related utilities.
version: 3.0.2
author: Tony Humbert <tony.humberts@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: ^0.17.0
  petitparser: ^4.1.0
  timezone: ^0.7.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
