name: date
description: Hour, Date, Month implementations for Dart and other time related utilities.
version: 2.2.0
author: Tony Humbert <tony.humberts@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  intl: '>=0.14.0 <1.0.0'
  petitparser: 2.0.0
  timezone: '>=0.5.5 <1.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: '>=1.3.0 <2.0.0'
