name: date
description: A simple Date implementation and other time related utilities.
version: 0.0.2
author: Tony Humbert <humbert.tony@yahoo.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  intl: '>=0.14.0 <0.15.0'
  timezone: '>=0.4.3 <0.5.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
