name: date
description: Hour, Date, Month implementations for Dart and other time related utilities.
version: 2.2.0
author: Tony Humbert <tony.humberts@gmail.com>

environment:
  sdk: '>2.0.0-dev.61.0 <3.0.0'

dependencies:
  intl: '>=0.14.0 <0.16.0'
  petitparser: 2.0.0
  timezone: ^0.5.0-dev-3

dev_dependencies:
  test: '>=1.3.0'
